pysecurity/do_not_browse/apps/bbb_tutorial/urls.py
from django import urls

from . import views

app_name = "tutorial"
urlpatterns = [
    urls.path("", views.TutorialOneView.as_view(), name="one"),
    urls.path("two/", views.TutorialTwoView.as_view(), name="two"),
]

pysecurity/do_not_browse/pysecurity/urls.py
from django import conf, urls
from django.conf.urls.static import static
from django.contrib import admin
from django.templatetags.static import static as reverse_static
from django.views.generic import base

urlpatterns = [
    urls.path("admin/", admin.site.urls),
    urls.path("accounts/", urls.include("django.contrib.auth.urls")),
    urls.path("", urls.include("apps.aaa_core.urls")),
    urls.path("tutorial/", urls.include("apps.bbb_tutorial.urls")),
    urls.path("ccc/", urls.include("apps.ccc_simple_injection.urls")),
    urls.path("ddd/", urls.include("apps.ddd_simple_sql_injection.urls")),
    urls.path("eee/", urls.include("apps.eee_nostradamus.urls")),
    urls.path("fff/", urls.include("apps.fff_meegeren.urls")),
    urls.path("ggg/", urls.include("apps.ggg_priorities.urls")),
    urls.path("hhh/", urls.include("apps.hhh_claims.urls")),
    urls.path(
        "favicon.ico",
        base.RedirectView.as_view(url=reverse_static("favicon.ico"), permanent=True),
    ),
] + static(conf.settings.STATIC_URL, document_root=conf.settings.STATIC_ROOT)

pysecurity/do_not_browse/apps/bbb_tutorial/models.py
from django.db import models


class TutorialTwoNote(models.Model):
    class Classification(models.TextChoices):
        PUBLIC = "PUB", "Public"
        PRIVATE = "PRI", "Private"

    classification = models.CharField(
        max_length=3,
        choices=Classification.choices,
    )
    note = models.TextField()
    author = models.CharField(max_length=32)

pysecurity/do_not_browse/apps/bbb_tutorial/views/one.py
from django import http
from django.views import generic


class TutorialOneView(generic.TemplateView):
    """The Tutorial view."""

    template_name = "tutorial/one.html"

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        """Check if the value was modified."""
        posted_value = request.POST.get("username", None)
        if posted_value is None:
            return http.HttpResponseBadRequest()

        status = "failure" if posted_value == "sebastiaan" else "success"
        context = self.get_context_data(status=status, posted_value=posted_value)
        return self.render_to_response(context)

pysecurity/do_not_browse/apps/bbb_tutorial/views/two.py
import traceback
from typing import Any

from django import db, http
from django.views import generic

from .. import models


class TutorialTwoView(generic.TemplateView):
    """The Tutorial view."""

    template_name = "tutorial/two.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        author_filter = kwargs.pop("author_filter", None)
        if author_filter:
            queryset = models.TutorialTwoNote.objects.raw(
                f"""
                SELECT * FROM tutorial_tutorialtwonote
                WHERE classification='PUB'
                AND author='{author_filter}'
                """
            )
        else:
            queryset = models.TutorialTwoNote.objects.raw(
                """
                SELECT * FROM tutorial_tutorialtwonote
                WHERE classification='PUB'
                """
            )
        notes = None
        try:
            notes = list(queryset)
        except db.DatabaseError as exception:
            db_error = "".join(traceback.format_exception(exception))
        else:
            db_error = None

        return super().get_context_data(**kwargs, notes=notes, db_error=db_error)

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        """Check if the value was modified."""
        author_filter = request.POST.get("author_filter", None)
        context = self.get_context_data(author_filter=author_filter)
        return self.render_to_response(context)

pysecurity/do_not_browse/apps/ccc_simple_injection/views/one.py
from typing import Any

from django import http
from django.contrib.auth import mixins
from django.views import generic

from .. import models


class SimpleInjectionView(mixins.LoginRequiredMixin, generic.TemplateView):
    """The Tutorial view."""

    template_name = "ccc/one.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        user_id = kwargs.pop("user_id", self.request.user.pk)
        query = kwargs.pop("query", None)

        if query:
            qs = models.PrivateNote.objects.filter(
                author_id=user_id, note__contains=query
            )
        else:
            qs = models.PrivateNote.objects.filter(author_id=user_id)
        return super().get_context_data(notes=qs, **kwargs)

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        user_id = request.POST.get("user_id")
        query = request.POST.get("query")

        if not user_id:
            return http.HttpResponseBadRequest("No bueno!")

        context = self.get_context_data(user_id=user_id, query=query)
        return self.render_to_response(context)

pysecurity/do_not_browse/apps/ddd_simple_sql_injection/views/one.py
from typing import Any

from django import http
from django.contrib.auth import mixins
from django.views import generic

from .. import models


class SimpleSQLInjectionView(mixins.LoginRequiredMixin, generic.TemplateView):
    """The Tutorial view."""

    template_name = "ddd/one.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        author_id = self.request.user.pk
        query = kwargs.pop("query", None)
        if query:
            sql = rf"""
            SELECT * FROM simple_sql_injection_privatenoteddd WHERE note LIKE '%{query}%' ESCAPE '\' AND author_id = {author_id}
            """
            qs = models.PrivateNoteDDD.objects.raw(sql)
        else:
            qs = models.PrivateNoteDDD.objects.filter(author_id=author_id)
        return super().get_context_data(notes=list(qs), **kwargs)

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        user_id = request.POST.get("user_id")
        query = request.POST.get("query")

        if not user_id:
            return http.HttpResponseBadRequest("No bueno!")

        context = self.get_context_data(query=query)
        return self.render_to_response(context)

pysecurity/do_not_browse/apps/eee_nostradamus/views/one.py
from typing import Any

from django import http
from django.contrib.auth import mixins
from django.db import models as db_models
from django.views import generic

from .. import models


class Nostradamus(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = "eee/one.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        query = kwargs.pop("query", None)
        q_object = db_models.Q(author_id=self.request.user.pk)
        if query:
            q_object &= db_models.Q(note__contains=query)

        qs = models.PrivateNoteEEE.objects.filter(q_object)

        return super().get_context_data(notes=list(qs), **kwargs)

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        user_id = request.POST.get("user_id")
        query = request.POST.get("query")

        if not user_id:
            return http.HttpResponseBadRequest("No bueno!")

        context = self.get_context_data(query=query)
        return self.render_to_response(context)


class Note(generic.DetailView):
    model = models.PrivateNoteEEE
    template_name = "eee/note.html"
    context_object_name = "note"

pysecurity/do_not_browse/apps/fff_meegeren/views/one.py
import logging
from typing import Any

import jwt
from django import http
from django.contrib.auth import mixins
from django.core import exceptions
from django.db import models as db_models
from django.views import generic

from .. import models

log = logging.getLogger(__name__)


class UserPassesTestOr404Mixin(mixins.UserPassesTestMixin):
    def handle_no_permission(self) -> http.HttpResponseRedirect:
        try:
            response = super().handle_no_permission()
        except exceptions.PermissionDenied as e:
            raise http.Http404("No notes matches the given query.") from e
        return response


class Nostradamus(UserPassesTestOr404Mixin, generic.TemplateView):
    template_name = "fff/one.html"

    def test_func(self) -> bool | None:
        session_key = self.request.session.session_key
        token = self.request.COOKIES.get("token")
        try:
            decoded_token = jwt.decode(
                token,
                key="very-secure-key-for-jwt",
                options={"verify_signature": True},
                algorithms=["HS256"],
            )
        except jwt.InvalidTokenError as e:
            log.exception(f"Invalid token found!")
            return False

        if decoded_token.get("session") != session_key:
            return False

        return decoded_token.get("user_id") == self.request.user.pk

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        query = kwargs.pop("query", None)
        q_object = db_models.Q(author_id=self.request.user.pk)
        if query:
            q_object &= db_models.Q(note__contains=query)

        qs = models.PrivateNoteFFF.objects.filter(q_object)
        return super().get_context_data(notes=list(qs), **kwargs)

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        user_id = request.POST.get("user_id")
        query = request.POST.get("query")

        if not user_id:
            return http.HttpResponseBadRequest("No bueno!")

        context = self.get_context_data(query=query)
        return self.render_to_response(context)


class Note(UserPassesTestOr404Mixin, generic.DetailView):
    model = models.PrivateNoteFFF
    template_name = "fff/note.html"
    context_object_name = "note"

    def test_func(self) -> bool | None:
        session_key = self.request.session.session_key
        token = self.request.COOKIES.get("token")
        try:
            decoded_token = jwt.decode(
                token,
                key="very-secure-key-for-jwt",
                options={"verify_signature": False},
                algorithms=["HS256"],
            )
        except jwt.InvalidTokenError as e:
            log.exception(f"Invalid token found!")
            return False

        if decoded_token.get("session") != session_key:
            return False

        note = self.get_object()
        return decoded_token.get("user_id") == note.author_id

pysecurity/do_not_browse/apps/ggg_priorities/views/one.py
import logging

from django import http
from django.contrib.auth import mixins
from django.views import generic

from .. import models

log = logging.getLogger(__name__)


class Priorities(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = "ggg/one.html"

    # def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
    #     query = kwargs.pop("query", None)
    #     q_object = db_models.Q(author_id=self.request.user.pk)
    #     if query:
    #         q_object &= db_models.Q(note__contains=query)
    #
    #     qs = models.PrioritizedNotes.objects.filter(q_object)
    #     return super().get_context_data(notes=list(qs), **kwargs)

    def post(self, request: http.HttpRequest) -> http.HttpResponse:
        priority = request.POST.get("priority")
        if priority:
            qs = models.PrioritizedNotes.objects.raw(
                f"""
                SELECT * FROM priorities_prioritizednotes WHERE priority = '{priority}' AND author_id = {request.user.pk}
                """
            )
        else:
            qs = models.PrioritizedNotes.objects.filter(author_id=request.user.pk)

        serialized = [
            {
                "author": str(note.author),
                "priority": note.get_priority_display(),
                "note": note.note,
            }
            for note in qs
        ]

        return http.JsonResponse(serialized, safe=False)

pysecurity/do_not_browse/apps/hhh_claims/views/one.py
import datetime
import io
import logging
from typing import Any

import jwt
from django import http, urls
from django.contrib.auth import mixins
from django.contrib.auth import models as auth_models
from django.utils import timezone
from django.views import generic

log = logging.getLogger(__name__)


class Priorities(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = "hhh/one.html"

    @staticmethod
    def post(request: http.HttpRequest, *args: Any, **kwargs: Any) -> http.JsonResponse:
        expiry = (timezone.now() + datetime.timedelta(minutes=5)).timestamp()
        user_id = request.user.pk
        user_data_url = urls.reverse("hhh:user-data", kwargs={"user_id": user_id})
        token = jwt.encode(
            {
                "user_id": user_id,
                "expiry": expiry,
                "claims": {
                    "allowed_download": user_data_url,
                },
            },
            "very-secure-download-token-key",
            algorithm="HS256",
        )
        reversed_token = "".join(reversed(token))
        return http.JsonResponse({"url": user_data_url, "token": reversed_token})


class DownloadUserData(mixins.LoginRequiredMixin, generic.View):
    def get(self, request: http.HttpRequest, user_id: int) -> http.FileResponse:
        authorization_header = request.headers.get("Authorization")
        if not authorization_header or not authorization_header.startswith("token "):
            return http.FileResponse(self._invalid_file())

        _, _, token = authorization_header.partition(" ")
        try:
            decoded_token = jwt.decode(
                token,
                key="very-secure-download-token-key",
                options={"verify_signature": False},
                algorithms=["HS256"],
            )
        except jwt.InvalidTokenError:
            return http.FileResponse(self._invalid_file())

        try:
            download_url = decoded_token["claims"]["allowed_download"]
        except KeyError:
            return http.FileResponse(self._invalid_file())
        if download_url != request.path:
            return http.FileResponse(self._invalid_file())

        try:
            token_user_id = decoded_token["user_id"]
        except KeyError:
            return http.FileResponse(self._invalid_file())
        if user_id != token_user_id:
            return http.FileResponse(self._invalid_file())

        match token_user_id:
            case 1:
                text = (
                    "Marvin's user data.\n\nThis is not the Paranoid Android you're"
                    " looking for."
                )
                file = io.BytesIO(text.encode("utf-8"))
            case 2:
                text = (
                    "Arthur's data!\n\nSecret code:"
                    " the-restaurant-at-the-end-of-the-workshop"
                )
                file = io.BytesIO(text.encode("utf-8"))
            case _:
                file = self._invalid_file()

        return http.FileResponse(file)

    def _invalid_file(self) -> io.BytesIO:
        return io.BytesIO("Error: This download is not valid".encode("utf-8"))

pysecurity/do_not_browse/apps/bbb_tutorial/templates/tutorial/one.html
{% extends "core/base.html" %}

{% block title %}Tutorial — Part 1{% endblock title %}
{% block body %}
<h1>Tutorial Part One</h1>
<h2>Exercises</h2>
<ol>
    <li>Set a breakpoint in ZAP that will intercept traffic from this page.</li>
    <li>Press the button below.</li>
    <li>Use ZAP to change the value of `username` in the request payload to something other than "sebastiaan".</li>
    <li>Check the result.</li>
</ol>
<div style="margin: 20px 0;">
<form method="POST" action="">
    {% csrf_token %}
    <input type="hidden" name="username" value="sebastiaan">
    <button type="submit">Make POST request</button>
</form>
</div>
{% if posted_value %}
    <p id="result-message">
        {% if status == "success" %}
            That's right! You posted '{{ posted_value }}'.
        {% else %}
            Something went wrong, the value of username is still '{{ posted_value }}'.
        {% endif %}
    </p>
{% endif %}
    {% if status == "success" %}
        <p><button type="button" onclick="location.href='{% url 'tutorial:two' %}';">Go to part two!</button></p>
    {% endif %}
{% endblock body %}

pysecurity/do_not_browse/apps/bbb_tutorial/templates/tutorial/two.html
{% extends "core/base.html" %}

{% block css %}
    th, td {
        padding: 5px 10px;
    }
    th {
        text-align: left;
    }

    .code {
        font-family: monospace;
        display: inline-block;
        padding: 0 5px;
        background-color: #CCC;
    }

{% endblock css %}

{% block title %}Tutorial — Part 2{% endblock title %}
{% block body %}
    <h1>Tutorial Part Two</h1>
    <p>
        You don't always have to use ZAP to find the vulnerability. This page lists all
        public notes. Our goal is also list private entries using SQL Injection by using
        the author filter input.
    </p>

    <h2>Exercises</h2>
    <ol>
        <li>Filter the list by the author name "Jeremy"</li>
        <li>Filter the list by the unknown author name "Esther"</li>
        <li>Try filtering by a single quote character, <span class="code">'</span></li>
        <li>Now try this as a filter: <span class="code">' OR '1</span></li>
    </ol>
    <div style="margin: 20px 0;">
    <form method="POST" action="" style="display: inline-block;">
        {% csrf_token %}
        <input type="text" name="author_filter" placeholder="Filter by author">
        <button type="submit">Filter by author</button>
    </form>
    <form method="POST" action="" style="display: inline-block;">
        {% csrf_token %}
        <input type="hidden" name="author_filter" value="">
        <button type="submit">Reset filter</button>
    </form>
    </div>

    {% if notes %}
    <table>
        <thead>
            <tr>
                <th>Classification</th>
                <th>Author</th>
                <th>Note</th>
            </tr>
        </thead>
        <tbody>
            {% for note in notes %}
                <tr>
                    <td>{{ note.get_classification_display }}</td>
                    <td>{{ note.author }}</td>
                    <td>{{ note.note }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No notes matching your query.</p>
    {% endif %}

    {% if notes|length_is:"3"  %}
        <h3>Why does this work?</h3>
        <p>
            It's because of unsafe formatting of a SQL query. In this case, the name of
            the author is interpolated into the SQL query using an f-string instead of
            using proper query parameterization.
        </p>
        <p>
            The original query defined in the code is this:
        </p>
        <pre>
query = f"""
    SELECT * FROM tutorial_tutorialtwonote
    WHERE classification='PUB' AND author='{author_filter}'
"""
        </pre>
        <p>If we then interpolate the string <span class="code">' OR '1</span>, we get:</p>
        <pre>
query = """
    SELECT * FROM tutorial_tutorialtwonote
    WHERE classification='PUB' AND author='' OR '1'
"""
        </pre>
        <p>
            This is still valid SQL, but since AND has a higher precedence than OR, the
            WHERE-clause now reduces down to [RESULT OF AND] OR [TRUE]. No matter the
            result of the AND clause, using an OR with something that is always truthy
            means that the entire condition is always truthy.
        </p>
        <p>
            And, just like that, all notes have a truthy WHERE clause.
        </p>
        <p>
            Secret code: im-so-meta-even-this-acronym
        </p>
    {% endif %}
{% endblock body %}